### ISSUE TITLE
Pitch change

### ISSUE THREAD

**Issue by Elizahub** [SonyCSLParis/pesto#12]
How can I change the pitch? For example, my input audio is C4 audio. I want to get audio without distortion, but, for example F5. Is it possible to do this with your tool?

**Comment by aRI0U** [comment]
Hi! Unfortunately, our tool only enables you to estimate the pitch of an audio, i.e., it can tell you that your C4 audio is actually a C4.

However, there are several tools to do pitch-shifting, you can use librosa for example. Note though that for a huge pitch shift (C4 to F5), you may still have artifacts in the resulting signal

**Comment by ElizavetaSedova** [comment]
@aRI0U Thanks for the answer! I decided to test your tool and noticed one feature. I tested multiple input audio files . All of them contain the sound of E3 notes only. I always get 52 Hz along the entire length. But 52 Hz is not E3. Do I understand correctly that the ratio of notes and frequencies is not standard? I expected to get 164 Hz or similar.
